apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: client_3000
        image: applied-devops:client_3000
        ports:
        - containerPort: 3000
      - name: server_3000
        image: applied-devops:server_3000
        ports:
        - containerPort: 3010
