apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: web-app-3000
        image: your-ecr-repo-name:web_app_3000
        ports:
        - containerPort: 3000
      - name: web-app-3010
        image: your-ecr-repo-name:web_app_3010
        ports:
        - containerPort: 3010
